### ISSUE TITLE
Support OAK-D SR PoE

### ISSUE THREAD

**Issue by dmn-seasony** [luxonis/depthai-viewer#53]
The latest version of depthai-viewer crashes when I try to connect the SR PoE camera. Just updating the depthai library should be enough, I managed to get it working locally by changing the version tag here to 2.25.0.0:
https://github.com/luxonis/depthai-viewer/blob/ea0cdb3130d041f47ca6587309ba49f0109ee579/rerun_py/depthai_viewer/requirements.txt#L7

Side note: I noticed that the latest version of `depthai-sdk` currently depends on `depthai==2.22.0.0`. The only reason it works in this case is because `depthai==2.25.0.0` is installed after `depthai-sdk`. The SDK should not need to be locked to a specific minor release if semantic versioning is followed.

**Comment by zrezke** [comment]
Awesome - thanks for looking into it already - will fix this as you suggested (dai 2.25 includes the new revision of oak d sr poe boards). 
I agree with the versioning there - at least in the viewer we install it in a separate venv to not influence the system wide depthai version. Perhaps the sdk should have bundled it's own depthai version as the viewer does... anyways we will not fix this in the sdk as it's deprecated - we will rather make depthai more capable.

**Comment by zrezke** [comment]
We've got pretty good OAK-D-SR-POE support now, since: https://github.com/luxonis/depthai-viewer/releases/tag/v0.2.0. Closing this issue.
