### ISSUE TITLE
Disable left/right streams on OAK-D-LR by default

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai-viewer#59]
Currently (0.2), when connecting OAK-D-LR to viewer it will have a latency of about 1sec. This is because we're streaming too many streams (>160MB/sec), so even USB3 link can't keep up, which causes delays on the whole pipeline.
We should either lower FPS, or disable left/right stream by default when viewer detects OAK-D-LR so the first UX will be smooth.

**Comment by zrezke** [comment]
I lowered the FPS to 10 and switched off the AI model by default. The UX is better now, will be in release 0.2.1.

**Comment by zrezke** [comment]
Closing as the improvements are released.
